os:
  - osx
language: swift
osx_image: xcode11
env:
  - PROJECT_NAME=Weak
install: 
  - (swift package update)
script:
  - (swift build)
  - (swift test)
after_success:
  - bash <(curl -s https://codecov.io/bash) -J "^Weak$" 
